/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CrmControllerGetCrmLogCountParams,
  CrmControllerGetCrmLogListParams,
  GetCrmLogCountResponse,
  GetCrmLogListResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const crmControllerGetCrmLogList = (
    params: CrmControllerGetCrmLogListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCrmLogListResponse>(
      {url: `/crm`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getCrmControllerGetCrmLogListQueryKey = (params?: CrmControllerGetCrmLogListParams,) => {
    return [
    `/crm`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCrmControllerGetCrmLogListQueryOptions = <TData = Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError = unknown>(params: CrmControllerGetCrmLogListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCrmControllerGetCrmLogListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof crmControllerGetCrmLogList>>> = ({ signal }) => crmControllerGetCrmLogList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CrmControllerGetCrmLogListQueryResult = NonNullable<Awaited<ReturnType<typeof crmControllerGetCrmLogList>>>
export type CrmControllerGetCrmLogListQueryError = unknown


export function useCrmControllerGetCrmLogList<TData = Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError = unknown>(
 params: CrmControllerGetCrmLogListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof crmControllerGetCrmLogList>>,
          TError,
          Awaited<ReturnType<typeof crmControllerGetCrmLogList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCrmControllerGetCrmLogList<TData = Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError = unknown>(
 params: CrmControllerGetCrmLogListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof crmControllerGetCrmLogList>>,
          TError,
          Awaited<ReturnType<typeof crmControllerGetCrmLogList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCrmControllerGetCrmLogList<TData = Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError = unknown>(
 params: CrmControllerGetCrmLogListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCrmControllerGetCrmLogList<TData = Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError = unknown>(
 params: CrmControllerGetCrmLogListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCrmControllerGetCrmLogListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const crmControllerGetCrmLogCount = (
    params: CrmControllerGetCrmLogCountParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCrmLogCountResponse>(
      {url: `/crm/count`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getCrmControllerGetCrmLogCountQueryKey = (params?: CrmControllerGetCrmLogCountParams,) => {
    return [
    `/crm/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCrmControllerGetCrmLogCountQueryOptions = <TData = Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError = unknown>(params: CrmControllerGetCrmLogCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCrmControllerGetCrmLogCountQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>> = ({ signal }) => crmControllerGetCrmLogCount(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CrmControllerGetCrmLogCountQueryResult = NonNullable<Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>>
export type CrmControllerGetCrmLogCountQueryError = unknown


export function useCrmControllerGetCrmLogCount<TData = Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError = unknown>(
 params: CrmControllerGetCrmLogCountParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>,
          TError,
          Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCrmControllerGetCrmLogCount<TData = Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError = unknown>(
 params: CrmControllerGetCrmLogCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>,
          TError,
          Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCrmControllerGetCrmLogCount<TData = Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError = unknown>(
 params: CrmControllerGetCrmLogCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCrmControllerGetCrmLogCount<TData = Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError = unknown>(
 params: CrmControllerGetCrmLogCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crmControllerGetCrmLogCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCrmControllerGetCrmLogCountQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



