/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CloseStoreRequest,
  CloseStoreResponse,
  OpenStoreRequest,
  OpenStoreResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const storeOperationControllerOpenStore = (
    openStoreRequest: OpenStoreRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OpenStoreResponse>(
      {url: `/store-operation/open`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: openStoreRequest, signal
    },
      options);
    }
  


export const getStoreOperationControllerOpenStoreMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeOperationControllerOpenStore>>, TError,{data: OpenStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof storeOperationControllerOpenStore>>, TError,{data: OpenStoreRequest}, TContext> => {

const mutationKey = ['storeOperationControllerOpenStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeOperationControllerOpenStore>>, {data: OpenStoreRequest}> = (props) => {
          const {data} = props ?? {};

          return  storeOperationControllerOpenStore(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StoreOperationControllerOpenStoreMutationResult = NonNullable<Awaited<ReturnType<typeof storeOperationControllerOpenStore>>>
    export type StoreOperationControllerOpenStoreMutationBody = OpenStoreRequest
    export type StoreOperationControllerOpenStoreMutationError = unknown

    export const useStoreOperationControllerOpenStore = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeOperationControllerOpenStore>>, TError,{data: OpenStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeOperationControllerOpenStore>>,
        TError,
        {data: OpenStoreRequest},
        TContext
      > => {

      const mutationOptions = getStoreOperationControllerOpenStoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const storeOperationControllerCloseStore = (
    closeStoreRequest: CloseStoreRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CloseStoreResponse>(
      {url: `/store-operation/close`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: closeStoreRequest, signal
    },
      options);
    }
  


export const getStoreOperationControllerCloseStoreMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeOperationControllerCloseStore>>, TError,{data: CloseStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof storeOperationControllerCloseStore>>, TError,{data: CloseStoreRequest}, TContext> => {

const mutationKey = ['storeOperationControllerCloseStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeOperationControllerCloseStore>>, {data: CloseStoreRequest}> = (props) => {
          const {data} = props ?? {};

          return  storeOperationControllerCloseStore(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StoreOperationControllerCloseStoreMutationResult = NonNullable<Awaited<ReturnType<typeof storeOperationControllerCloseStore>>>
    export type StoreOperationControllerCloseStoreMutationBody = CloseStoreRequest
    export type StoreOperationControllerCloseStoreMutationError = unknown

    export const useStoreOperationControllerCloseStore = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeOperationControllerCloseStore>>, TError,{data: CloseStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeOperationControllerCloseStore>>,
        TError,
        {data: CloseStoreRequest},
        TContext
      > => {

      const mutationOptions = getStoreOperationControllerCloseStoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    