/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ChangeStoreAdminPasswordRequest,
  PartnersLoginRequest
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const authControllerPartnersAdminLogin = (
    partnersLoginRequest: PartnersLoginRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: partnersLoginRequest, signal
    },
      options);
    }
  


export const getAuthControllerPartnersAdminLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerPartnersAdminLogin>>, TError,{data: PartnersLoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerPartnersAdminLogin>>, TError,{data: PartnersLoginRequest}, TContext> => {

const mutationKey = ['authControllerPartnersAdminLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerPartnersAdminLogin>>, {data: PartnersLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerPartnersAdminLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerPartnersAdminLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerPartnersAdminLogin>>>
    export type AuthControllerPartnersAdminLoginMutationBody = PartnersLoginRequest
    export type AuthControllerPartnersAdminLoginMutationError = unknown

    export const useAuthControllerPartnersAdminLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerPartnersAdminLogin>>, TError,{data: PartnersLoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerPartnersAdminLogin>>,
        TError,
        {data: PartnersLoginRequest},
        TContext
      > => {

      const mutationOptions = getAuthControllerPartnersAdminLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerGetNewAccessToken = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/refresh`, method: 'POST', signal
    },
      options);
    }
  


export const getAuthControllerGetNewAccessTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>, TError,void, TContext> => {

const mutationKey = ['authControllerGetNewAccessToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>, void> = () => {
          

          return  authControllerGetNewAccessToken(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerGetNewAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>>
    
    export type AuthControllerGetNewAccessTokenMutationError = unknown

    export const useAuthControllerGetNewAccessToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerGetNewAccessToken>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerGetNewAccessTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerPartnersAdminlogout = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getAuthControllerPartnersAdminlogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerPartnersAdminlogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerPartnersAdminlogout>>, TError,void, TContext> => {

const mutationKey = ['authControllerPartnersAdminlogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerPartnersAdminlogout>>, void> = () => {
          

          return  authControllerPartnersAdminlogout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerPartnersAdminlogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerPartnersAdminlogout>>>
    
    export type AuthControllerPartnersAdminlogoutMutationError = unknown

    export const useAuthControllerPartnersAdminlogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerPartnersAdminlogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerPartnersAdminlogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerPartnersAdminlogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerChangeStoreAdminPassword = (
    changeStoreAdminPasswordRequest: ChangeStoreAdminPasswordRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/auth/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changeStoreAdminPasswordRequest
    },
      options);
    }
  


export const getAuthControllerChangeStoreAdminPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerChangeStoreAdminPassword>>, TError,{data: ChangeStoreAdminPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerChangeStoreAdminPassword>>, TError,{data: ChangeStoreAdminPasswordRequest}, TContext> => {

const mutationKey = ['authControllerChangeStoreAdminPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerChangeStoreAdminPassword>>, {data: ChangeStoreAdminPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerChangeStoreAdminPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerChangeStoreAdminPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerChangeStoreAdminPassword>>>
    export type AuthControllerChangeStoreAdminPasswordMutationBody = ChangeStoreAdminPasswordRequest
    export type AuthControllerChangeStoreAdminPasswordMutationError = unknown

    export const useAuthControllerChangeStoreAdminPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerChangeStoreAdminPassword>>, TError,{data: ChangeStoreAdminPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerChangeStoreAdminPassword>>,
        TError,
        {data: ChangeStoreAdminPasswordRequest},
        TContext
      > => {

      const mutationOptions = getAuthControllerChangeStoreAdminPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    