/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetStoreOilPriceResponse,
  OilPriceControllerGetStoreOilPriceParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const oilPriceControllerGetStoreOilPrice = (
    params: OilPriceControllerGetStoreOilPriceParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreOilPriceResponse>(
      {url: `/oil-price`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getOilPriceControllerGetStoreOilPriceQueryKey = (params?: OilPriceControllerGetStoreOilPriceParams,) => {
    return [
    `/oil-price`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getOilPriceControllerGetStoreOilPriceQueryOptions = <TData = Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError = unknown>(params: OilPriceControllerGetStoreOilPriceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOilPriceControllerGetStoreOilPriceQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>> = ({ signal }) => oilPriceControllerGetStoreOilPrice(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OilPriceControllerGetStoreOilPriceQueryResult = NonNullable<Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>>
export type OilPriceControllerGetStoreOilPriceQueryError = unknown


export function useOilPriceControllerGetStoreOilPrice<TData = Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError = unknown>(
 params: OilPriceControllerGetStoreOilPriceParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>,
          TError,
          Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOilPriceControllerGetStoreOilPrice<TData = Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError = unknown>(
 params: OilPriceControllerGetStoreOilPriceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>,
          TError,
          Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOilPriceControllerGetStoreOilPrice<TData = Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError = unknown>(
 params: OilPriceControllerGetStoreOilPriceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOilPriceControllerGetStoreOilPrice<TData = Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError = unknown>(
 params: OilPriceControllerGetStoreOilPriceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oilPriceControllerGetStoreOilPrice>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOilPriceControllerGetStoreOilPriceQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



