/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetOfflineTicketListResponse,
  OfflineTicketControllerGetOfflineTicketListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const offlineTicketControllerGetOfflineTicketList = (
    params: OfflineTicketControllerGetOfflineTicketListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetOfflineTicketListResponse>(
      {url: `/offline-ticket`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getOfflineTicketControllerGetOfflineTicketListQueryKey = (params?: OfflineTicketControllerGetOfflineTicketListParams,) => {
    return [
    `/offline-ticket`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getOfflineTicketControllerGetOfflineTicketListQueryOptions = <TData = Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError = unknown>(params: OfflineTicketControllerGetOfflineTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOfflineTicketControllerGetOfflineTicketListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>> = ({ signal }) => offlineTicketControllerGetOfflineTicketList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OfflineTicketControllerGetOfflineTicketListQueryResult = NonNullable<Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>>
export type OfflineTicketControllerGetOfflineTicketListQueryError = unknown


export function useOfflineTicketControllerGetOfflineTicketList<TData = Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError = unknown>(
 params: OfflineTicketControllerGetOfflineTicketListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>,
          TError,
          Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOfflineTicketControllerGetOfflineTicketList<TData = Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError = unknown>(
 params: OfflineTicketControllerGetOfflineTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>,
          TError,
          Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOfflineTicketControllerGetOfflineTicketList<TData = Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError = unknown>(
 params: OfflineTicketControllerGetOfflineTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOfflineTicketControllerGetOfflineTicketList<TData = Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError = unknown>(
 params: OfflineTicketControllerGetOfflineTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof offlineTicketControllerGetOfflineTicketList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOfflineTicketControllerGetOfflineTicketListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



