/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateDailyFuelStockSummaryRequest,
  CreateDailyFuelStockSummaryResponse,
  DeleteDailyFuelStockSummaryResponse,
  FuelStockControllerGetDailyFuelStockSummaryDetailParams,
  FuelStockControllerGetMonthlyFuelStockSummaryListParams,
  GetDailyFuelStockSummaryDetailByIdResponse,
  GetDailyFuelStockSummaryDetailResponse,
  GetMonthlyFuelStockSummaryListResponse,
  UpdateDailyFuelStockSummaryRequest,
  UpdateDailyFuelStockSummaryResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const fuelStockControllerCreateDailyFuelStockSummary = (
    createDailyFuelStockSummaryRequest: CreateDailyFuelStockSummaryRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateDailyFuelStockSummaryResponse>(
      {url: `/fuel-stock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDailyFuelStockSummaryRequest, signal
    },
      options);
    }
  


export const getFuelStockControllerCreateDailyFuelStockSummaryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fuelStockControllerCreateDailyFuelStockSummary>>, TError,{data: CreateDailyFuelStockSummaryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof fuelStockControllerCreateDailyFuelStockSummary>>, TError,{data: CreateDailyFuelStockSummaryRequest}, TContext> => {

const mutationKey = ['fuelStockControllerCreateDailyFuelStockSummary'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fuelStockControllerCreateDailyFuelStockSummary>>, {data: CreateDailyFuelStockSummaryRequest}> = (props) => {
          const {data} = props ?? {};

          return  fuelStockControllerCreateDailyFuelStockSummary(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FuelStockControllerCreateDailyFuelStockSummaryMutationResult = NonNullable<Awaited<ReturnType<typeof fuelStockControllerCreateDailyFuelStockSummary>>>
    export type FuelStockControllerCreateDailyFuelStockSummaryMutationBody = CreateDailyFuelStockSummaryRequest
    export type FuelStockControllerCreateDailyFuelStockSummaryMutationError = unknown

    export const useFuelStockControllerCreateDailyFuelStockSummary = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fuelStockControllerCreateDailyFuelStockSummary>>, TError,{data: CreateDailyFuelStockSummaryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fuelStockControllerCreateDailyFuelStockSummary>>,
        TError,
        {data: CreateDailyFuelStockSummaryRequest},
        TContext
      > => {

      const mutationOptions = getFuelStockControllerCreateDailyFuelStockSummaryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const fuelStockControllerUpdateDailyFuelStockSummary = (
    updateDailyFuelStockSummaryRequest: UpdateDailyFuelStockSummaryRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateDailyFuelStockSummaryResponse>(
      {url: `/fuel-stock/update`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateDailyFuelStockSummaryRequest
    },
      options);
    }
  


export const getFuelStockControllerUpdateDailyFuelStockSummaryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fuelStockControllerUpdateDailyFuelStockSummary>>, TError,{data: UpdateDailyFuelStockSummaryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof fuelStockControllerUpdateDailyFuelStockSummary>>, TError,{data: UpdateDailyFuelStockSummaryRequest}, TContext> => {

const mutationKey = ['fuelStockControllerUpdateDailyFuelStockSummary'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fuelStockControllerUpdateDailyFuelStockSummary>>, {data: UpdateDailyFuelStockSummaryRequest}> = (props) => {
          const {data} = props ?? {};

          return  fuelStockControllerUpdateDailyFuelStockSummary(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FuelStockControllerUpdateDailyFuelStockSummaryMutationResult = NonNullable<Awaited<ReturnType<typeof fuelStockControllerUpdateDailyFuelStockSummary>>>
    export type FuelStockControllerUpdateDailyFuelStockSummaryMutationBody = UpdateDailyFuelStockSummaryRequest
    export type FuelStockControllerUpdateDailyFuelStockSummaryMutationError = unknown

    export const useFuelStockControllerUpdateDailyFuelStockSummary = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fuelStockControllerUpdateDailyFuelStockSummary>>, TError,{data: UpdateDailyFuelStockSummaryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fuelStockControllerUpdateDailyFuelStockSummary>>,
        TError,
        {data: UpdateDailyFuelStockSummaryRequest},
        TContext
      > => {

      const mutationOptions = getFuelStockControllerUpdateDailyFuelStockSummaryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const fuelStockControllerGetMonthlyFuelStockSummaryList = (
    params: FuelStockControllerGetMonthlyFuelStockSummaryListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetMonthlyFuelStockSummaryListResponse>(
      {url: `/fuel-stock/monthly`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFuelStockControllerGetMonthlyFuelStockSummaryListQueryKey = (params?: FuelStockControllerGetMonthlyFuelStockSummaryListParams,) => {
    return [
    `/fuel-stock/monthly`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFuelStockControllerGetMonthlyFuelStockSummaryListQueryOptions = <TData = Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError = unknown>(params: FuelStockControllerGetMonthlyFuelStockSummaryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFuelStockControllerGetMonthlyFuelStockSummaryListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>> = ({ signal }) => fuelStockControllerGetMonthlyFuelStockSummaryList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FuelStockControllerGetMonthlyFuelStockSummaryListQueryResult = NonNullable<Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>>
export type FuelStockControllerGetMonthlyFuelStockSummaryListQueryError = unknown


export function useFuelStockControllerGetMonthlyFuelStockSummaryList<TData = Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError = unknown>(
 params: FuelStockControllerGetMonthlyFuelStockSummaryListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>,
          TError,
          Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelStockControllerGetMonthlyFuelStockSummaryList<TData = Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError = unknown>(
 params: FuelStockControllerGetMonthlyFuelStockSummaryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>,
          TError,
          Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelStockControllerGetMonthlyFuelStockSummaryList<TData = Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError = unknown>(
 params: FuelStockControllerGetMonthlyFuelStockSummaryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFuelStockControllerGetMonthlyFuelStockSummaryList<TData = Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError = unknown>(
 params: FuelStockControllerGetMonthlyFuelStockSummaryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetMonthlyFuelStockSummaryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFuelStockControllerGetMonthlyFuelStockSummaryListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const fuelStockControllerGetDailyFuelStockSummaryDetail = (
    params: FuelStockControllerGetDailyFuelStockSummaryDetailParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetDailyFuelStockSummaryDetailResponse>(
      {url: `/fuel-stock/daily`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFuelStockControllerGetDailyFuelStockSummaryDetailQueryKey = (params?: FuelStockControllerGetDailyFuelStockSummaryDetailParams,) => {
    return [
    `/fuel-stock/daily`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFuelStockControllerGetDailyFuelStockSummaryDetailQueryOptions = <TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError = unknown>(params: FuelStockControllerGetDailyFuelStockSummaryDetailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFuelStockControllerGetDailyFuelStockSummaryDetailQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>> = ({ signal }) => fuelStockControllerGetDailyFuelStockSummaryDetail(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FuelStockControllerGetDailyFuelStockSummaryDetailQueryResult = NonNullable<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>>
export type FuelStockControllerGetDailyFuelStockSummaryDetailQueryError = unknown


export function useFuelStockControllerGetDailyFuelStockSummaryDetail<TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError = unknown>(
 params: FuelStockControllerGetDailyFuelStockSummaryDetailParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>,
          TError,
          Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelStockControllerGetDailyFuelStockSummaryDetail<TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError = unknown>(
 params: FuelStockControllerGetDailyFuelStockSummaryDetailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>,
          TError,
          Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelStockControllerGetDailyFuelStockSummaryDetail<TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError = unknown>(
 params: FuelStockControllerGetDailyFuelStockSummaryDetailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFuelStockControllerGetDailyFuelStockSummaryDetail<TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError = unknown>(
 params: FuelStockControllerGetDailyFuelStockSummaryDetailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFuelStockControllerGetDailyFuelStockSummaryDetailQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const fuelStockControllerGetDailyFuelStockSummaryDetailById = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetDailyFuelStockSummaryDetailByIdResponse>(
      {url: `/fuel-stock/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getFuelStockControllerGetDailyFuelStockSummaryDetailByIdQueryKey = (id?: string,) => {
    return [
    `/fuel-stock/${id}`
    ] as const;
    }

    
export const getFuelStockControllerGetDailyFuelStockSummaryDetailByIdQueryOptions = <TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFuelStockControllerGetDailyFuelStockSummaryDetailByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>> = ({ signal }) => fuelStockControllerGetDailyFuelStockSummaryDetailById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FuelStockControllerGetDailyFuelStockSummaryDetailByIdQueryResult = NonNullable<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>>
export type FuelStockControllerGetDailyFuelStockSummaryDetailByIdQueryError = unknown


export function useFuelStockControllerGetDailyFuelStockSummaryDetailById<TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>,
          TError,
          Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelStockControllerGetDailyFuelStockSummaryDetailById<TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>,
          TError,
          Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelStockControllerGetDailyFuelStockSummaryDetailById<TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFuelStockControllerGetDailyFuelStockSummaryDetailById<TData = Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelStockControllerGetDailyFuelStockSummaryDetailById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFuelStockControllerGetDailyFuelStockSummaryDetailByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const fuelStockControllerDeleteDailyFuelStockSummary = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteDailyFuelStockSummaryResponse>(
      {url: `/fuel-stock/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getFuelStockControllerDeleteDailyFuelStockSummaryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fuelStockControllerDeleteDailyFuelStockSummary>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof fuelStockControllerDeleteDailyFuelStockSummary>>, TError,{id: string}, TContext> => {

const mutationKey = ['fuelStockControllerDeleteDailyFuelStockSummary'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fuelStockControllerDeleteDailyFuelStockSummary>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  fuelStockControllerDeleteDailyFuelStockSummary(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FuelStockControllerDeleteDailyFuelStockSummaryMutationResult = NonNullable<Awaited<ReturnType<typeof fuelStockControllerDeleteDailyFuelStockSummary>>>
    
    export type FuelStockControllerDeleteDailyFuelStockSummaryMutationError = unknown

    export const useFuelStockControllerDeleteDailyFuelStockSummary = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fuelStockControllerDeleteDailyFuelStockSummary>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fuelStockControllerDeleteDailyFuelStockSummary>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getFuelStockControllerDeleteDailyFuelStockSummaryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    