/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetServiceStatByHourResponse,
  GetServiceStatByPassTypeResponse,
  GetServiceStatByWeekdayResponse,
  GetTotalServicesResponse,
  ServiceControllerGetServiceStatByHourParams,
  ServiceControllerGetServiceStatByPassTypeParams,
  ServiceControllerGetServiceStatByWeekdayParams,
  ServiceControllerGetTotalServicesParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const serviceControllerGetTotalServices = (
    params?: ServiceControllerGetTotalServicesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTotalServicesResponse>(
      {url: `/service/total`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getServiceControllerGetTotalServicesQueryKey = (params?: ServiceControllerGetTotalServicesParams,) => {
    return [
    `/service/total`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getServiceControllerGetTotalServicesQueryOptions = <TData = Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError = unknown>(params?: ServiceControllerGetTotalServicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServiceControllerGetTotalServicesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serviceControllerGetTotalServices>>> = ({ signal }) => serviceControllerGetTotalServices(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServiceControllerGetTotalServicesQueryResult = NonNullable<Awaited<ReturnType<typeof serviceControllerGetTotalServices>>>
export type ServiceControllerGetTotalServicesQueryError = unknown


export function useServiceControllerGetTotalServices<TData = Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError = unknown>(
 params: undefined |  ServiceControllerGetTotalServicesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerGetTotalServices>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerGetTotalServices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerGetTotalServices<TData = Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError = unknown>(
 params?: ServiceControllerGetTotalServicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerGetTotalServices>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerGetTotalServices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerGetTotalServices<TData = Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError = unknown>(
 params?: ServiceControllerGetTotalServicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServiceControllerGetTotalServices<TData = Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError = unknown>(
 params?: ServiceControllerGetTotalServicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetTotalServices>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServiceControllerGetTotalServicesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const serviceControllerGetServiceStatByPassType = (
    params?: ServiceControllerGetServiceStatByPassTypeParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetServiceStatByPassTypeResponse>(
      {url: `/service/stat/pass-type`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getServiceControllerGetServiceStatByPassTypeQueryKey = (params?: ServiceControllerGetServiceStatByPassTypeParams,) => {
    return [
    `/service/stat/pass-type`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getServiceControllerGetServiceStatByPassTypeQueryOptions = <TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError = unknown>(params?: ServiceControllerGetServiceStatByPassTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServiceControllerGetServiceStatByPassTypeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>> = ({ signal }) => serviceControllerGetServiceStatByPassType(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServiceControllerGetServiceStatByPassTypeQueryResult = NonNullable<Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>>
export type ServiceControllerGetServiceStatByPassTypeQueryError = unknown


export function useServiceControllerGetServiceStatByPassType<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError = unknown>(
 params: undefined |  ServiceControllerGetServiceStatByPassTypeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerGetServiceStatByPassType<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError = unknown>(
 params?: ServiceControllerGetServiceStatByPassTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerGetServiceStatByPassType<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError = unknown>(
 params?: ServiceControllerGetServiceStatByPassTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServiceControllerGetServiceStatByPassType<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError = unknown>(
 params?: ServiceControllerGetServiceStatByPassTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByPassType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServiceControllerGetServiceStatByPassTypeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const serviceControllerGetServiceStatByWeekday = (
    params?: ServiceControllerGetServiceStatByWeekdayParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetServiceStatByWeekdayResponse>(
      {url: `/service/stat/weekday`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getServiceControllerGetServiceStatByWeekdayQueryKey = (params?: ServiceControllerGetServiceStatByWeekdayParams,) => {
    return [
    `/service/stat/weekday`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getServiceControllerGetServiceStatByWeekdayQueryOptions = <TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError = unknown>(params?: ServiceControllerGetServiceStatByWeekdayParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServiceControllerGetServiceStatByWeekdayQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>> = ({ signal }) => serviceControllerGetServiceStatByWeekday(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServiceControllerGetServiceStatByWeekdayQueryResult = NonNullable<Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>>
export type ServiceControllerGetServiceStatByWeekdayQueryError = unknown


export function useServiceControllerGetServiceStatByWeekday<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError = unknown>(
 params: undefined |  ServiceControllerGetServiceStatByWeekdayParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerGetServiceStatByWeekday<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError = unknown>(
 params?: ServiceControllerGetServiceStatByWeekdayParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerGetServiceStatByWeekday<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError = unknown>(
 params?: ServiceControllerGetServiceStatByWeekdayParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServiceControllerGetServiceStatByWeekday<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError = unknown>(
 params?: ServiceControllerGetServiceStatByWeekdayParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByWeekday>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServiceControllerGetServiceStatByWeekdayQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const serviceControllerGetServiceStatByHour = (
    params?: ServiceControllerGetServiceStatByHourParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetServiceStatByHourResponse>(
      {url: `/service/stat/hour`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getServiceControllerGetServiceStatByHourQueryKey = (params?: ServiceControllerGetServiceStatByHourParams,) => {
    return [
    `/service/stat/hour`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getServiceControllerGetServiceStatByHourQueryOptions = <TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError = unknown>(params?: ServiceControllerGetServiceStatByHourParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServiceControllerGetServiceStatByHourQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>> = ({ signal }) => serviceControllerGetServiceStatByHour(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServiceControllerGetServiceStatByHourQueryResult = NonNullable<Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>>
export type ServiceControllerGetServiceStatByHourQueryError = unknown


export function useServiceControllerGetServiceStatByHour<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError = unknown>(
 params: undefined |  ServiceControllerGetServiceStatByHourParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerGetServiceStatByHour<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError = unknown>(
 params?: ServiceControllerGetServiceStatByHourParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>,
          TError,
          Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceControllerGetServiceStatByHour<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError = unknown>(
 params?: ServiceControllerGetServiceStatByHourParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServiceControllerGetServiceStatByHour<TData = Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError = unknown>(
 params?: ServiceControllerGetServiceStatByHourParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceControllerGetServiceStatByHour>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServiceControllerGetServiceStatByHourQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



