/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FreeWashControllerGetFreeWashHistoryListParams,
  GetFreeWashHistoryListResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const freeWashControllerGetFreeWashHistoryList = (
    params: FreeWashControllerGetFreeWashHistoryListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetFreeWashHistoryListResponse>(
      {url: `/free-wash`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFreeWashControllerGetFreeWashHistoryListQueryKey = (params?: FreeWashControllerGetFreeWashHistoryListParams,) => {
    return [
    `/free-wash`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFreeWashControllerGetFreeWashHistoryListQueryOptions = <TData = Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError = unknown>(params: FreeWashControllerGetFreeWashHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFreeWashControllerGetFreeWashHistoryListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>> = ({ signal }) => freeWashControllerGetFreeWashHistoryList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FreeWashControllerGetFreeWashHistoryListQueryResult = NonNullable<Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>>
export type FreeWashControllerGetFreeWashHistoryListQueryError = unknown


export function useFreeWashControllerGetFreeWashHistoryList<TData = Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError = unknown>(
 params: FreeWashControllerGetFreeWashHistoryListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>,
          TError,
          Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFreeWashControllerGetFreeWashHistoryList<TData = Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError = unknown>(
 params: FreeWashControllerGetFreeWashHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>,
          TError,
          Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFreeWashControllerGetFreeWashHistoryList<TData = Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError = unknown>(
 params: FreeWashControllerGetFreeWashHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFreeWashControllerGetFreeWashHistoryList<TData = Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError = unknown>(
 params: FreeWashControllerGetFreeWashHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof freeWashControllerGetFreeWashHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFreeWashControllerGetFreeWashHistoryListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



