/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMoMMarketingROIResponse,
  GetVisitCohortResponse,
  MarketingControllerGetMoMMarketingROIParams,
  MarketingControllerGetVisitCohortParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const marketingControllerGetMoMMarketingROI = (
    params: MarketingControllerGetMoMMarketingROIParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetMoMMarketingROIResponse>(
      {url: `/marketing/roi/mom`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getMarketingControllerGetMoMMarketingROIQueryKey = (params?: MarketingControllerGetMoMMarketingROIParams,) => {
    return [
    `/marketing/roi/mom`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getMarketingControllerGetMoMMarketingROIQueryOptions = <TData = Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError = unknown>(params: MarketingControllerGetMoMMarketingROIParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketingControllerGetMoMMarketingROIQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>> = ({ signal }) => marketingControllerGetMoMMarketingROI(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MarketingControllerGetMoMMarketingROIQueryResult = NonNullable<Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>>
export type MarketingControllerGetMoMMarketingROIQueryError = unknown


export function useMarketingControllerGetMoMMarketingROI<TData = Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError = unknown>(
 params: MarketingControllerGetMoMMarketingROIParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>,
          TError,
          Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMarketingControllerGetMoMMarketingROI<TData = Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError = unknown>(
 params: MarketingControllerGetMoMMarketingROIParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>,
          TError,
          Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMarketingControllerGetMoMMarketingROI<TData = Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError = unknown>(
 params: MarketingControllerGetMoMMarketingROIParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMarketingControllerGetMoMMarketingROI<TData = Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError = unknown>(
 params: MarketingControllerGetMoMMarketingROIParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetMoMMarketingROI>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMarketingControllerGetMoMMarketingROIQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const marketingControllerGetVisitCohort = (
    params: MarketingControllerGetVisitCohortParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetVisitCohortResponse>(
      {url: `/marketing/cohort/visit`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getMarketingControllerGetVisitCohortQueryKey = (params?: MarketingControllerGetVisitCohortParams,) => {
    return [
    `/marketing/cohort/visit`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getMarketingControllerGetVisitCohortQueryOptions = <TData = Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError = unknown>(params: MarketingControllerGetVisitCohortParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketingControllerGetVisitCohortQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>> = ({ signal }) => marketingControllerGetVisitCohort(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MarketingControllerGetVisitCohortQueryResult = NonNullable<Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>>
export type MarketingControllerGetVisitCohortQueryError = unknown


export function useMarketingControllerGetVisitCohort<TData = Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError = unknown>(
 params: MarketingControllerGetVisitCohortParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>,
          TError,
          Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMarketingControllerGetVisitCohort<TData = Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError = unknown>(
 params: MarketingControllerGetVisitCohortParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>,
          TError,
          Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMarketingControllerGetVisitCohort<TData = Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError = unknown>(
 params: MarketingControllerGetVisitCohortParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMarketingControllerGetVisitCohort<TData = Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError = unknown>(
 params: MarketingControllerGetVisitCohortParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof marketingControllerGetVisitCohort>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMarketingControllerGetVisitCohortQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



