/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FuelSalesControllerGetSalesByFuelTypeParams,
  FuelSalesControllerGetSalesStatByFuelTypeParams,
  GetSalesByFuelTypeResponse,
  GetSalesStatByFuelTypeResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const fuelSalesControllerGetSalesByFuelType = (
    params?: FuelSalesControllerGetSalesByFuelTypeParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSalesByFuelTypeResponse>(
      {url: `/fuel-sales/fuel-type`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFuelSalesControllerGetSalesByFuelTypeQueryKey = (params?: FuelSalesControllerGetSalesByFuelTypeParams,) => {
    return [
    `/fuel-sales/fuel-type`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFuelSalesControllerGetSalesByFuelTypeQueryOptions = <TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError = unknown>(params?: FuelSalesControllerGetSalesByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFuelSalesControllerGetSalesByFuelTypeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>> = ({ signal }) => fuelSalesControllerGetSalesByFuelType(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FuelSalesControllerGetSalesByFuelTypeQueryResult = NonNullable<Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>>
export type FuelSalesControllerGetSalesByFuelTypeQueryError = unknown


export function useFuelSalesControllerGetSalesByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError = unknown>(
 params: undefined |  FuelSalesControllerGetSalesByFuelTypeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>,
          TError,
          Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelSalesControllerGetSalesByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetSalesByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>,
          TError,
          Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelSalesControllerGetSalesByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetSalesByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFuelSalesControllerGetSalesByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetSalesByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFuelSalesControllerGetSalesByFuelTypeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const fuelSalesControllerGetSalesStatByFuelType = (
    params?: FuelSalesControllerGetSalesStatByFuelTypeParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSalesStatByFuelTypeResponse>(
      {url: `/fuel-sales/fuel-type/stat`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFuelSalesControllerGetSalesStatByFuelTypeQueryKey = (params?: FuelSalesControllerGetSalesStatByFuelTypeParams,) => {
    return [
    `/fuel-sales/fuel-type/stat`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFuelSalesControllerGetSalesStatByFuelTypeQueryOptions = <TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError = unknown>(params?: FuelSalesControllerGetSalesStatByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFuelSalesControllerGetSalesStatByFuelTypeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>> = ({ signal }) => fuelSalesControllerGetSalesStatByFuelType(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FuelSalesControllerGetSalesStatByFuelTypeQueryResult = NonNullable<Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>>
export type FuelSalesControllerGetSalesStatByFuelTypeQueryError = unknown


export function useFuelSalesControllerGetSalesStatByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError = unknown>(
 params: undefined |  FuelSalesControllerGetSalesStatByFuelTypeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>,
          TError,
          Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelSalesControllerGetSalesStatByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetSalesStatByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>,
          TError,
          Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelSalesControllerGetSalesStatByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetSalesStatByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFuelSalesControllerGetSalesStatByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetSalesStatByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetSalesStatByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFuelSalesControllerGetSalesStatByFuelTypeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



