/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FuelSalesControllerGetFuelSalesByFuelTypeParams,
  FuelSalesControllerGetFuelSalesStatByFuelTypeParams,
  GetFuelSalesByFuelTypeResponse,
  GetFuelSalesStatByFuelTypeResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const fuelSalesControllerGetFuelSalesByFuelType = (
    params?: FuelSalesControllerGetFuelSalesByFuelTypeParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetFuelSalesByFuelTypeResponse>(
      {url: `/fuel-sales/fuel-type`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFuelSalesControllerGetFuelSalesByFuelTypeQueryKey = (params?: FuelSalesControllerGetFuelSalesByFuelTypeParams,) => {
    return [
    `/fuel-sales/fuel-type`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFuelSalesControllerGetFuelSalesByFuelTypeQueryOptions = <TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError = unknown>(params?: FuelSalesControllerGetFuelSalesByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFuelSalesControllerGetFuelSalesByFuelTypeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>> = ({ signal }) => fuelSalesControllerGetFuelSalesByFuelType(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FuelSalesControllerGetFuelSalesByFuelTypeQueryResult = NonNullable<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>>
export type FuelSalesControllerGetFuelSalesByFuelTypeQueryError = unknown


export function useFuelSalesControllerGetFuelSalesByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError = unknown>(
 params: undefined |  FuelSalesControllerGetFuelSalesByFuelTypeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>,
          TError,
          Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelSalesControllerGetFuelSalesByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetFuelSalesByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>,
          TError,
          Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelSalesControllerGetFuelSalesByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetFuelSalesByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFuelSalesControllerGetFuelSalesByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetFuelSalesByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFuelSalesControllerGetFuelSalesByFuelTypeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const fuelSalesControllerGetFuelSalesStatByFuelType = (
    params?: FuelSalesControllerGetFuelSalesStatByFuelTypeParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetFuelSalesStatByFuelTypeResponse>(
      {url: `/fuel-sales/fuel-type/stat`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFuelSalesControllerGetFuelSalesStatByFuelTypeQueryKey = (params?: FuelSalesControllerGetFuelSalesStatByFuelTypeParams,) => {
    return [
    `/fuel-sales/fuel-type/stat`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFuelSalesControllerGetFuelSalesStatByFuelTypeQueryOptions = <TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError = unknown>(params?: FuelSalesControllerGetFuelSalesStatByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFuelSalesControllerGetFuelSalesStatByFuelTypeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>> = ({ signal }) => fuelSalesControllerGetFuelSalesStatByFuelType(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FuelSalesControllerGetFuelSalesStatByFuelTypeQueryResult = NonNullable<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>>
export type FuelSalesControllerGetFuelSalesStatByFuelTypeQueryError = unknown


export function useFuelSalesControllerGetFuelSalesStatByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError = unknown>(
 params: undefined |  FuelSalesControllerGetFuelSalesStatByFuelTypeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>,
          TError,
          Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelSalesControllerGetFuelSalesStatByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetFuelSalesStatByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>,
          TError,
          Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFuelSalesControllerGetFuelSalesStatByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetFuelSalesStatByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFuelSalesControllerGetFuelSalesStatByFuelType<TData = Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError = unknown>(
 params?: FuelSalesControllerGetFuelSalesStatByFuelTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fuelSalesControllerGetFuelSalesStatByFuelType>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFuelSalesControllerGetFuelSalesStatByFuelTypeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



