/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMonthlySalesResponse,
  SalesControllerGetMonthlySalesParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const salesControllerGetMonthlySales = (
    params: SalesControllerGetMonthlySalesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetMonthlySalesResponse>(
      {url: `/sales/monthly`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSalesControllerGetMonthlySalesQueryKey = (params?: SalesControllerGetMonthlySalesParams,) => {
    return [
    `/sales/monthly`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSalesControllerGetMonthlySalesQueryOptions = <TData = Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError = unknown>(params: SalesControllerGetMonthlySalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSalesControllerGetMonthlySalesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof salesControllerGetMonthlySales>>> = ({ signal }) => salesControllerGetMonthlySales(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SalesControllerGetMonthlySalesQueryResult = NonNullable<Awaited<ReturnType<typeof salesControllerGetMonthlySales>>>
export type SalesControllerGetMonthlySalesQueryError = unknown


export function useSalesControllerGetMonthlySales<TData = Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError = unknown>(
 params: SalesControllerGetMonthlySalesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof salesControllerGetMonthlySales>>,
          TError,
          Awaited<ReturnType<typeof salesControllerGetMonthlySales>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSalesControllerGetMonthlySales<TData = Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError = unknown>(
 params: SalesControllerGetMonthlySalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof salesControllerGetMonthlySales>>,
          TError,
          Awaited<ReturnType<typeof salesControllerGetMonthlySales>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSalesControllerGetMonthlySales<TData = Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError = unknown>(
 params: SalesControllerGetMonthlySalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSalesControllerGetMonthlySales<TData = Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError = unknown>(
 params: SalesControllerGetMonthlySalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof salesControllerGetMonthlySales>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSalesControllerGetMonthlySalesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



