/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ChangeStoreAdminPasswordRequest,
  ChangeStoreAdminPasswordResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const adminControllerChangeStoreAdminPassword = (
    changeStoreAdminPasswordRequest: ChangeStoreAdminPasswordRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ChangeStoreAdminPasswordResponse>(
      {url: `/admin/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changeStoreAdminPasswordRequest
    },
      options);
    }
  


export const getAdminControllerChangeStoreAdminPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>, TError,{data: ChangeStoreAdminPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>, TError,{data: ChangeStoreAdminPasswordRequest}, TContext> => {

const mutationKey = ['adminControllerChangeStoreAdminPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>, {data: ChangeStoreAdminPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  adminControllerChangeStoreAdminPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminControllerChangeStoreAdminPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>>
    export type AdminControllerChangeStoreAdminPasswordMutationBody = ChangeStoreAdminPasswordRequest
    export type AdminControllerChangeStoreAdminPasswordMutationError = unknown

    export const useAdminControllerChangeStoreAdminPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>, TError,{data: ChangeStoreAdminPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>,
        TError,
        {data: ChangeStoreAdminPasswordRequest},
        TContext
      > => {

      const mutationOptions = getAdminControllerChangeStoreAdminPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    