/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangeStoreAdminPasswordRequest,
  ChangeStoreAdminPasswordResponse,
  GetStoreAdminProfileResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const adminControllerGetStoreAdminProfile = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreAdminProfileResponse>(
      {url: `/admin/profile`, method: 'GET', signal
    },
      options);
    }
  



export const getAdminControllerGetStoreAdminProfileQueryKey = () => {
    return [
    `/admin/profile`
    ] as const;
    }

    
export const getAdminControllerGetStoreAdminProfileQueryOptions = <TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetStoreAdminProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>> = ({ signal }) => adminControllerGetStoreAdminProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetStoreAdminProfileQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>>
export type AdminControllerGetStoreAdminProfileQueryError = unknown


export function useAdminControllerGetStoreAdminProfile<TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetStoreAdminProfile<TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetStoreAdminProfile<TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAdminControllerGetStoreAdminProfile<TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetStoreAdminProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const adminControllerChangeStoreAdminPassword = (
    changeStoreAdminPasswordRequest: ChangeStoreAdminPasswordRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ChangeStoreAdminPasswordResponse>(
      {url: `/admin/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changeStoreAdminPasswordRequest
    },
      options);
    }
  


export const getAdminControllerChangeStoreAdminPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>, TError,{data: ChangeStoreAdminPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>, TError,{data: ChangeStoreAdminPasswordRequest}, TContext> => {

const mutationKey = ['adminControllerChangeStoreAdminPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>, {data: ChangeStoreAdminPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  adminControllerChangeStoreAdminPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminControllerChangeStoreAdminPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>>
    export type AdminControllerChangeStoreAdminPasswordMutationBody = ChangeStoreAdminPasswordRequest
    export type AdminControllerChangeStoreAdminPasswordMutationError = unknown

    export const useAdminControllerChangeStoreAdminPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>, TError,{data: ChangeStoreAdminPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminControllerChangeStoreAdminPassword>>,
        TError,
        {data: ChangeStoreAdminPasswordRequest},
        TContext
      > => {

      const mutationOptions = getAdminControllerChangeStoreAdminPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    