/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExportUserListRequest,
  GetUserDetailResponse,
  GetUserListResponse,
  GetUsersCountResponse,
  UserControllerGetUserListParams,
  UserControllerGetUsersCountParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const userControllerGetUserList = (
    params: UserControllerGetUserListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserListResponse>(
      {url: `/user`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getUserControllerGetUserListQueryKey = (params?: UserControllerGetUserListParams,) => {
    return [
    `/user`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getUserControllerGetUserListQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetUserList>>, TError = unknown>(params: UserControllerGetUserListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetUserListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetUserList>>> = ({ signal }) => userControllerGetUserList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetUserListQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetUserList>>>
export type UserControllerGetUserListQueryError = unknown


export function useUserControllerGetUserList<TData = Awaited<ReturnType<typeof userControllerGetUserList>>, TError = unknown>(
 params: UserControllerGetUserListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserList>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUserList<TData = Awaited<ReturnType<typeof userControllerGetUserList>>, TError = unknown>(
 params: UserControllerGetUserListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserList>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUserList<TData = Awaited<ReturnType<typeof userControllerGetUserList>>, TError = unknown>(
 params: UserControllerGetUserListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerGetUserList<TData = Awaited<ReturnType<typeof userControllerGetUserList>>, TError = unknown>(
 params: UserControllerGetUserListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetUserListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const userControllerGetUsersCount = (
    params?: UserControllerGetUsersCountParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUsersCountResponse>(
      {url: `/user/count`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getUserControllerGetUsersCountQueryKey = (params?: UserControllerGetUsersCountParams,) => {
    return [
    `/user/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getUserControllerGetUsersCountQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError = unknown>(params?: UserControllerGetUsersCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetUsersCountQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetUsersCount>>> = ({ signal }) => userControllerGetUsersCount(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetUsersCountQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetUsersCount>>>
export type UserControllerGetUsersCountQueryError = unknown


export function useUserControllerGetUsersCount<TData = Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError = unknown>(
 params: undefined |  UserControllerGetUsersCountParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUsersCount>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUsersCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUsersCount<TData = Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError = unknown>(
 params?: UserControllerGetUsersCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUsersCount>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUsersCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUsersCount<TData = Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError = unknown>(
 params?: UserControllerGetUsersCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerGetUsersCount<TData = Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError = unknown>(
 params?: UserControllerGetUsersCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUsersCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetUsersCountQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const userControllerExportUserList = (
    exportUserListRequest: ExportUserListRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/user/export`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportUserListRequest, signal
    },
      options);
    }
  


export const getUserControllerExportUserListMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerExportUserList>>, TError,{data: ExportUserListRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerExportUserList>>, TError,{data: ExportUserListRequest}, TContext> => {

const mutationKey = ['userControllerExportUserList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerExportUserList>>, {data: ExportUserListRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerExportUserList(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerExportUserListMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerExportUserList>>>
    export type UserControllerExportUserListMutationBody = ExportUserListRequest
    export type UserControllerExportUserListMutationError = unknown

    export const useUserControllerExportUserList = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerExportUserList>>, TError,{data: ExportUserListRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerExportUserList>>,
        TError,
        {data: ExportUserListRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerExportUserListMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const userControllerGetUserDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserDetailResponse>(
      {url: `/user/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getUserControllerGetUserDetailQueryKey = (id?: string,) => {
    return [
    `/user/${id}`
    ] as const;
    }

    
export const getUserControllerGetUserDetailQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetUserDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetUserDetail>>> = ({ signal }) => userControllerGetUserDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetUserDetailQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetUserDetail>>>
export type UserControllerGetUserDetailQueryError = unknown


export function useUserControllerGetUserDetail<TData = Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserDetail>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUserDetail<TData = Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserDetail>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUserDetail<TData = Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerGetUserDetail<TData = Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetUserDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



