/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExportPaymentListRequest,
  GetPaymentListResponse,
  PaymentControllerGetPaymentListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const paymentControllerGetPaymentList = (
    params: PaymentControllerGetPaymentListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetPaymentListResponse>(
      {url: `/payment`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getPaymentControllerGetPaymentListQueryKey = (params?: PaymentControllerGetPaymentListParams,) => {
    return [
    `/payment`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPaymentControllerGetPaymentListQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError = unknown>(params: PaymentControllerGetPaymentListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerGetPaymentListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerGetPaymentList>>> = ({ signal }) => paymentControllerGetPaymentList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerGetPaymentListQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerGetPaymentList>>>
export type PaymentControllerGetPaymentListQueryError = unknown


export function usePaymentControllerGetPaymentList<TData = Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError = unknown>(
 params: PaymentControllerGetPaymentListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetPaymentList>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetPaymentList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetPaymentList<TData = Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError = unknown>(
 params: PaymentControllerGetPaymentListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetPaymentList>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetPaymentList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetPaymentList<TData = Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError = unknown>(
 params: PaymentControllerGetPaymentListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePaymentControllerGetPaymentList<TData = Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError = unknown>(
 params: PaymentControllerGetPaymentListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPaymentList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerGetPaymentListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const paymentControllerExportPaymentList = (
    exportPaymentListRequest: ExportPaymentListRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/payment/export`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportPaymentListRequest, signal
    },
      options);
    }
  


export const getPaymentControllerExportPaymentListMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerExportPaymentList>>, TError,{data: ExportPaymentListRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentControllerExportPaymentList>>, TError,{data: ExportPaymentListRequest}, TContext> => {

const mutationKey = ['paymentControllerExportPaymentList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentControllerExportPaymentList>>, {data: ExportPaymentListRequest}> = (props) => {
          const {data} = props ?? {};

          return  paymentControllerExportPaymentList(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PaymentControllerExportPaymentListMutationResult = NonNullable<Awaited<ReturnType<typeof paymentControllerExportPaymentList>>>
    export type PaymentControllerExportPaymentListMutationBody = ExportPaymentListRequest
    export type PaymentControllerExportPaymentListMutationError = unknown

    export const usePaymentControllerExportPaymentList = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerExportPaymentList>>, TError,{data: ExportPaymentListRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentControllerExportPaymentList>>,
        TError,
        {data: ExportPaymentListRequest},
        TContext
      > => {

      const mutationOptions = getPaymentControllerExportPaymentListMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    