/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetNoticeDetailResponse,
  GetNoticeListResponse,
  NoticeControllerGetNoticeListParams,
  RegisterNoticeRequest,
  RegisterNoticeResponse,
  UpdateNoticeRequest,
  UpdateNoticeResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const noticeControllerGetNoticeList = (
    params: NoticeControllerGetNoticeListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetNoticeListResponse>(
      {url: `/notice`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getNoticeControllerGetNoticeListQueryKey = (params?: NoticeControllerGetNoticeListParams,) => {
    return [
    `/notice`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getNoticeControllerGetNoticeListQueryOptions = <TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(params: NoticeControllerGetNoticeListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNoticeControllerGetNoticeListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>> = ({ signal }) => noticeControllerGetNoticeList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NoticeControllerGetNoticeListQueryResult = NonNullable<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>>
export type NoticeControllerGetNoticeListQueryError = unknown


export function useNoticeControllerGetNoticeList<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(
 params: NoticeControllerGetNoticeListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticeControllerGetNoticeList>>,
          TError,
          Awaited<ReturnType<typeof noticeControllerGetNoticeList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticeControllerGetNoticeList<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(
 params: NoticeControllerGetNoticeListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticeControllerGetNoticeList>>,
          TError,
          Awaited<ReturnType<typeof noticeControllerGetNoticeList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticeControllerGetNoticeList<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(
 params: NoticeControllerGetNoticeListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNoticeControllerGetNoticeList<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(
 params: NoticeControllerGetNoticeListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNoticeControllerGetNoticeListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const noticeControllerRegisterNotice = (
    registerNoticeRequest: RegisterNoticeRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterNoticeResponse>(
      {url: `/notice`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerNoticeRequest, signal
    },
      options);
    }
  


export const getNoticeControllerRegisterNoticeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticeControllerRegisterNotice>>, TError,{data: RegisterNoticeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof noticeControllerRegisterNotice>>, TError,{data: RegisterNoticeRequest}, TContext> => {

const mutationKey = ['noticeControllerRegisterNotice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof noticeControllerRegisterNotice>>, {data: RegisterNoticeRequest}> = (props) => {
          const {data} = props ?? {};

          return  noticeControllerRegisterNotice(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NoticeControllerRegisterNoticeMutationResult = NonNullable<Awaited<ReturnType<typeof noticeControllerRegisterNotice>>>
    export type NoticeControllerRegisterNoticeMutationBody = RegisterNoticeRequest
    export type NoticeControllerRegisterNoticeMutationError = unknown

    export const useNoticeControllerRegisterNotice = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticeControllerRegisterNotice>>, TError,{data: RegisterNoticeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof noticeControllerRegisterNotice>>,
        TError,
        {data: RegisterNoticeRequest},
        TContext
      > => {

      const mutationOptions = getNoticeControllerRegisterNoticeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const noticeControllerUpdateNotice = (
    updateNoticeRequest: UpdateNoticeRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateNoticeResponse>(
      {url: `/notice/update`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateNoticeRequest
    },
      options);
    }
  


export const getNoticeControllerUpdateNoticeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticeControllerUpdateNotice>>, TError,{data: UpdateNoticeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof noticeControllerUpdateNotice>>, TError,{data: UpdateNoticeRequest}, TContext> => {

const mutationKey = ['noticeControllerUpdateNotice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof noticeControllerUpdateNotice>>, {data: UpdateNoticeRequest}> = (props) => {
          const {data} = props ?? {};

          return  noticeControllerUpdateNotice(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NoticeControllerUpdateNoticeMutationResult = NonNullable<Awaited<ReturnType<typeof noticeControllerUpdateNotice>>>
    export type NoticeControllerUpdateNoticeMutationBody = UpdateNoticeRequest
    export type NoticeControllerUpdateNoticeMutationError = unknown

    export const useNoticeControllerUpdateNotice = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticeControllerUpdateNotice>>, TError,{data: UpdateNoticeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof noticeControllerUpdateNotice>>,
        TError,
        {data: UpdateNoticeRequest},
        TContext
      > => {

      const mutationOptions = getNoticeControllerUpdateNoticeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const noticeControllerGetNoticeDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetNoticeDetailResponse>(
      {url: `/notice/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getNoticeControllerGetNoticeDetailQueryKey = (id?: string,) => {
    return [
    `/notice/${id}`
    ] as const;
    }

    
export const getNoticeControllerGetNoticeDetailQueryOptions = <TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNoticeControllerGetNoticeDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>> = ({ signal }) => noticeControllerGetNoticeDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NoticeControllerGetNoticeDetailQueryResult = NonNullable<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>>
export type NoticeControllerGetNoticeDetailQueryError = unknown


export function useNoticeControllerGetNoticeDetail<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>,
          TError,
          Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticeControllerGetNoticeDetail<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>,
          TError,
          Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticeControllerGetNoticeDetail<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNoticeControllerGetNoticeDetail<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNoticeControllerGetNoticeDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const noticeControllerDeleteNotice = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateNoticeResponse>(
      {url: `/notice/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getNoticeControllerDeleteNoticeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticeControllerDeleteNotice>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof noticeControllerDeleteNotice>>, TError,{id: string}, TContext> => {

const mutationKey = ['noticeControllerDeleteNotice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof noticeControllerDeleteNotice>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  noticeControllerDeleteNotice(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NoticeControllerDeleteNoticeMutationResult = NonNullable<Awaited<ReturnType<typeof noticeControllerDeleteNotice>>>
    
    export type NoticeControllerDeleteNoticeMutationError = unknown

    export const useNoticeControllerDeleteNotice = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof noticeControllerDeleteNotice>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof noticeControllerDeleteNotice>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getNoticeControllerDeleteNoticeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    