/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetDailyWeatherHistoryListResponse,
  GetMonthlyWeatherHistoryListResponse,
  WeatherControllerGetDailyWeatherHistoryParams,
  WeatherControllerGetMonthlyWeatherHistoryListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const weatherControllerGetDailyWeatherHistory = (
    params: WeatherControllerGetDailyWeatherHistoryParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetDailyWeatherHistoryListResponse>(
      {url: `/weather/daily`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getWeatherControllerGetDailyWeatherHistoryQueryKey = (params?: WeatherControllerGetDailyWeatherHistoryParams,) => {
    return [
    `/weather/daily`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getWeatherControllerGetDailyWeatherHistoryQueryOptions = <TData = Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError = unknown>(params: WeatherControllerGetDailyWeatherHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWeatherControllerGetDailyWeatherHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>> = ({ signal }) => weatherControllerGetDailyWeatherHistory(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WeatherControllerGetDailyWeatherHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>>
export type WeatherControllerGetDailyWeatherHistoryQueryError = unknown


export function useWeatherControllerGetDailyWeatherHistory<TData = Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError = unknown>(
 params: WeatherControllerGetDailyWeatherHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>,
          TError,
          Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWeatherControllerGetDailyWeatherHistory<TData = Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError = unknown>(
 params: WeatherControllerGetDailyWeatherHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>,
          TError,
          Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWeatherControllerGetDailyWeatherHistory<TData = Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError = unknown>(
 params: WeatherControllerGetDailyWeatherHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWeatherControllerGetDailyWeatherHistory<TData = Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError = unknown>(
 params: WeatherControllerGetDailyWeatherHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetDailyWeatherHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWeatherControllerGetDailyWeatherHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const weatherControllerGetMonthlyWeatherHistoryList = (
    params: WeatherControllerGetMonthlyWeatherHistoryListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetMonthlyWeatherHistoryListResponse>(
      {url: `/weather/monthly`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getWeatherControllerGetMonthlyWeatherHistoryListQueryKey = (params?: WeatherControllerGetMonthlyWeatherHistoryListParams,) => {
    return [
    `/weather/monthly`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getWeatherControllerGetMonthlyWeatherHistoryListQueryOptions = <TData = Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError = unknown>(params: WeatherControllerGetMonthlyWeatherHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWeatherControllerGetMonthlyWeatherHistoryListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>> = ({ signal }) => weatherControllerGetMonthlyWeatherHistoryList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WeatherControllerGetMonthlyWeatherHistoryListQueryResult = NonNullable<Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>>
export type WeatherControllerGetMonthlyWeatherHistoryListQueryError = unknown


export function useWeatherControllerGetMonthlyWeatherHistoryList<TData = Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError = unknown>(
 params: WeatherControllerGetMonthlyWeatherHistoryListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>,
          TError,
          Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWeatherControllerGetMonthlyWeatherHistoryList<TData = Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError = unknown>(
 params: WeatherControllerGetMonthlyWeatherHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>,
          TError,
          Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWeatherControllerGetMonthlyWeatherHistoryList<TData = Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError = unknown>(
 params: WeatherControllerGetMonthlyWeatherHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWeatherControllerGetMonthlyWeatherHistoryList<TData = Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError = unknown>(
 params: WeatherControllerGetMonthlyWeatherHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetMonthlyWeatherHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWeatherControllerGetMonthlyWeatherHistoryListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



