/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DisconnectStaffRequest,
  DisconnectStaffResponse,
  GetStaffListResponse,
  RegisterStaffRequest,
  RegisterStaffResponse,
  StaffControllerGetStaffListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const staffControllerGetStaffList = (
    params: StaffControllerGetStaffListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStaffListResponse>(
      {url: `/staff`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStaffControllerGetStaffListQueryKey = (params?: StaffControllerGetStaffListParams,) => {
    return [
    `/staff`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStaffControllerGetStaffListQueryOptions = <TData = Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError = unknown>(params: StaffControllerGetStaffListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStaffControllerGetStaffListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof staffControllerGetStaffList>>> = ({ signal }) => staffControllerGetStaffList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StaffControllerGetStaffListQueryResult = NonNullable<Awaited<ReturnType<typeof staffControllerGetStaffList>>>
export type StaffControllerGetStaffListQueryError = unknown


export function useStaffControllerGetStaffList<TData = Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError = unknown>(
 params: StaffControllerGetStaffListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof staffControllerGetStaffList>>,
          TError,
          Awaited<ReturnType<typeof staffControllerGetStaffList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStaffControllerGetStaffList<TData = Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError = unknown>(
 params: StaffControllerGetStaffListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof staffControllerGetStaffList>>,
          TError,
          Awaited<ReturnType<typeof staffControllerGetStaffList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStaffControllerGetStaffList<TData = Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError = unknown>(
 params: StaffControllerGetStaffListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStaffControllerGetStaffList<TData = Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError = unknown>(
 params: StaffControllerGetStaffListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffControllerGetStaffList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStaffControllerGetStaffListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const staffControllerRegisterStaff = (
    registerStaffRequest: RegisterStaffRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterStaffResponse>(
      {url: `/staff/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerStaffRequest, signal
    },
      options);
    }
  


export const getStaffControllerRegisterStaffMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof staffControllerRegisterStaff>>, TError,{data: RegisterStaffRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof staffControllerRegisterStaff>>, TError,{data: RegisterStaffRequest}, TContext> => {

const mutationKey = ['staffControllerRegisterStaff'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof staffControllerRegisterStaff>>, {data: RegisterStaffRequest}> = (props) => {
          const {data} = props ?? {};

          return  staffControllerRegisterStaff(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StaffControllerRegisterStaffMutationResult = NonNullable<Awaited<ReturnType<typeof staffControllerRegisterStaff>>>
    export type StaffControllerRegisterStaffMutationBody = RegisterStaffRequest
    export type StaffControllerRegisterStaffMutationError = unknown

    export const useStaffControllerRegisterStaff = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof staffControllerRegisterStaff>>, TError,{data: RegisterStaffRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof staffControllerRegisterStaff>>,
        TError,
        {data: RegisterStaffRequest},
        TContext
      > => {

      const mutationOptions = getStaffControllerRegisterStaffMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const staffControllerDisconnectStaff = (
    disconnectStaffRequest: DisconnectStaffRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DisconnectStaffResponse>(
      {url: `/staff/disconnect`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: disconnectStaffRequest
    },
      options);
    }
  


export const getStaffControllerDisconnectStaffMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof staffControllerDisconnectStaff>>, TError,{data: DisconnectStaffRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof staffControllerDisconnectStaff>>, TError,{data: DisconnectStaffRequest}, TContext> => {

const mutationKey = ['staffControllerDisconnectStaff'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof staffControllerDisconnectStaff>>, {data: DisconnectStaffRequest}> = (props) => {
          const {data} = props ?? {};

          return  staffControllerDisconnectStaff(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StaffControllerDisconnectStaffMutationResult = NonNullable<Awaited<ReturnType<typeof staffControllerDisconnectStaff>>>
    export type StaffControllerDisconnectStaffMutationBody = DisconnectStaffRequest
    export type StaffControllerDisconnectStaffMutationError = unknown

    export const useStaffControllerDisconnectStaff = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof staffControllerDisconnectStaff>>, TError,{data: DisconnectStaffRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof staffControllerDisconnectStaff>>,
        TError,
        {data: DisconnectStaffRequest},
        TContext
      > => {

      const mutationOptions = getStaffControllerDisconnectStaffMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    