/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSubscriptionSnapshotListResponse,
  SubscriptionControllerGetSubscriptionSnapshotListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const subscriptionControllerGetSubscriptionSnapshotList = (
    params: SubscriptionControllerGetSubscriptionSnapshotListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSubscriptionSnapshotListResponse>(
      {url: `/subscription/snapshot`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSubscriptionControllerGetSubscriptionSnapshotListQueryKey = (params?: SubscriptionControllerGetSubscriptionSnapshotListParams,) => {
    return [
    `/subscription/snapshot`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSubscriptionControllerGetSubscriptionSnapshotListQueryOptions = <TData = Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError = unknown>(params: SubscriptionControllerGetSubscriptionSnapshotListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubscriptionControllerGetSubscriptionSnapshotListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>> = ({ signal }) => subscriptionControllerGetSubscriptionSnapshotList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubscriptionControllerGetSubscriptionSnapshotListQueryResult = NonNullable<Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>>
export type SubscriptionControllerGetSubscriptionSnapshotListQueryError = unknown


export function useSubscriptionControllerGetSubscriptionSnapshotList<TData = Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError = unknown>(
 params: SubscriptionControllerGetSubscriptionSnapshotListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>,
          TError,
          Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscriptionControllerGetSubscriptionSnapshotList<TData = Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError = unknown>(
 params: SubscriptionControllerGetSubscriptionSnapshotListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>,
          TError,
          Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscriptionControllerGetSubscriptionSnapshotList<TData = Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError = unknown>(
 params: SubscriptionControllerGetSubscriptionSnapshotListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSubscriptionControllerGetSubscriptionSnapshotList<TData = Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError = unknown>(
 params: SubscriptionControllerGetSubscriptionSnapshotListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionControllerGetSubscriptionSnapshotList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubscriptionControllerGetSubscriptionSnapshotListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



