/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  RefundCashPurchaseRequest,
  RefundCashPurchaseResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const purchaseControllerRefundCashPurchase = (
    refundCashPurchaseRequest: RefundCashPurchaseRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RefundCashPurchaseResponse>(
      {url: `/purchase/refund/cash`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refundCashPurchaseRequest, signal
    },
      options);
    }
  


export const getPurchaseControllerRefundCashPurchaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerRefundCashPurchase>>, TError,{data: RefundCashPurchaseRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerRefundCashPurchase>>, TError,{data: RefundCashPurchaseRequest}, TContext> => {

const mutationKey = ['purchaseControllerRefundCashPurchase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof purchaseControllerRefundCashPurchase>>, {data: RefundCashPurchaseRequest}> = (props) => {
          const {data} = props ?? {};

          return  purchaseControllerRefundCashPurchase(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PurchaseControllerRefundCashPurchaseMutationResult = NonNullable<Awaited<ReturnType<typeof purchaseControllerRefundCashPurchase>>>
    export type PurchaseControllerRefundCashPurchaseMutationBody = RefundCashPurchaseRequest
    export type PurchaseControllerRefundCashPurchaseMutationError = unknown

    export const usePurchaseControllerRefundCashPurchase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerRefundCashPurchase>>, TError,{data: RefundCashPurchaseRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof purchaseControllerRefundCashPurchase>>,
        TError,
        {data: RefundCashPurchaseRequest},
        TContext
      > => {

      const mutationOptions = getPurchaseControllerRefundCashPurchaseMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    