/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetManagedStoreListResponse,
  GetStoreDetailResponse,
  GetStoreListResponse,
  StoreControllerGetStoreListParams,
  UpdateStoreRequest,
  UpdateStoreResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const storeControllerGetStoreList = (
    params: StoreControllerGetStoreListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreListResponse>(
      {url: `/store`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStoreControllerGetStoreListQueryKey = (params?: StoreControllerGetStoreListParams,) => {
    return [
    `/store`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStoreControllerGetStoreListQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreList>>> = ({ signal }) => storeControllerGetStoreList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreListQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreList>>>
export type StoreControllerGetStoreListQueryError = unknown


export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerUpdateStore = (
    updateStoreRequest: UpdateStoreRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateStoreResponse>(
      {url: `/store/update`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateStoreRequest
    },
      options);
    }
  


export const getStoreControllerUpdateStoreMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeControllerUpdateStore>>, TError,{data: UpdateStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof storeControllerUpdateStore>>, TError,{data: UpdateStoreRequest}, TContext> => {

const mutationKey = ['storeControllerUpdateStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeControllerUpdateStore>>, {data: UpdateStoreRequest}> = (props) => {
          const {data} = props ?? {};

          return  storeControllerUpdateStore(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StoreControllerUpdateStoreMutationResult = NonNullable<Awaited<ReturnType<typeof storeControllerUpdateStore>>>
    export type StoreControllerUpdateStoreMutationBody = UpdateStoreRequest
    export type StoreControllerUpdateStoreMutationError = unknown

    export const useStoreControllerUpdateStore = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeControllerUpdateStore>>, TError,{data: UpdateStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeControllerUpdateStore>>,
        TError,
        {data: UpdateStoreRequest},
        TContext
      > => {

      const mutationOptions = getStoreControllerUpdateStoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const storeControllerGetManagedStoreList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetManagedStoreListResponse>(
      {url: `/store/managed`, method: 'GET', signal
    },
      options);
    }
  



export const getStoreControllerGetManagedStoreListQueryKey = () => {
    return [
    `/store/managed`
    ] as const;
    }

    
export const getStoreControllerGetManagedStoreListQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetManagedStoreListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>> = ({ signal }) => storeControllerGetManagedStoreList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetManagedStoreListQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>>
export type StoreControllerGetManagedStoreListQueryError = unknown


export function useStoreControllerGetManagedStoreList<TData = Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetManagedStoreList<TData = Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetManagedStoreList<TData = Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetManagedStoreList<TData = Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManagedStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetManagedStoreListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerGetStoreDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreDetailResponse>(
      {url: `/store/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getStoreControllerGetStoreDetailQueryKey = (id?: string,) => {
    return [
    `/store/${id}`
    ] as const;
    }

    
export const getStoreControllerGetStoreDetailQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>> = ({ signal }) => storeControllerGetStoreDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreDetailQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>>
export type StoreControllerGetStoreDetailQueryError = unknown


export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



