/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CancelServiceRequest,
  CancelServiceResponse,
  GetComplimentaryServiceHistoryListResponse,
  GetServiceHistoryListResponse,
  ServiceHistoryControllerGetComplimentaryServiceHistoryListParams,
  ServiceHistoryControllerGetServiceHistoryListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const serviceHistoryControllerGetServiceHistoryList = (
    params: ServiceHistoryControllerGetServiceHistoryListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetServiceHistoryListResponse>(
      {url: `/service-history`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getServiceHistoryControllerGetServiceHistoryListQueryKey = (params?: ServiceHistoryControllerGetServiceHistoryListParams,) => {
    return [
    `/service-history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getServiceHistoryControllerGetServiceHistoryListQueryOptions = <TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(params: ServiceHistoryControllerGetServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServiceHistoryControllerGetServiceHistoryListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>> = ({ signal }) => serviceHistoryControllerGetServiceHistoryList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServiceHistoryControllerGetServiceHistoryListQueryResult = NonNullable<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>>
export type ServiceHistoryControllerGetServiceHistoryListQueryError = unknown


export function useServiceHistoryControllerGetServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetServiceHistoryListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>,
          TError,
          Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceHistoryControllerGetServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>,
          TError,
          Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceHistoryControllerGetServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServiceHistoryControllerGetServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServiceHistoryControllerGetServiceHistoryListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const serviceHistoryControllerCancelService = (
    cancelServiceRequest: CancelServiceRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<CancelServiceResponse>(
      {url: `/service-history/cancel`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: cancelServiceRequest
    },
      options);
    }
  


export const getServiceHistoryControllerCancelServiceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceHistoryControllerCancelService>>, TError,{data: CancelServiceRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof serviceHistoryControllerCancelService>>, TError,{data: CancelServiceRequest}, TContext> => {

const mutationKey = ['serviceHistoryControllerCancelService'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof serviceHistoryControllerCancelService>>, {data: CancelServiceRequest}> = (props) => {
          const {data} = props ?? {};

          return  serviceHistoryControllerCancelService(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ServiceHistoryControllerCancelServiceMutationResult = NonNullable<Awaited<ReturnType<typeof serviceHistoryControllerCancelService>>>
    export type ServiceHistoryControllerCancelServiceMutationBody = CancelServiceRequest
    export type ServiceHistoryControllerCancelServiceMutationError = unknown

    export const useServiceHistoryControllerCancelService = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceHistoryControllerCancelService>>, TError,{data: CancelServiceRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof serviceHistoryControllerCancelService>>,
        TError,
        {data: CancelServiceRequest},
        TContext
      > => {

      const mutationOptions = getServiceHistoryControllerCancelServiceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const serviceHistoryControllerGetComplimentaryServiceHistoryList = (
    params: ServiceHistoryControllerGetComplimentaryServiceHistoryListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetComplimentaryServiceHistoryListResponse>(
      {url: `/service-history/complimentary`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getServiceHistoryControllerGetComplimentaryServiceHistoryListQueryKey = (params?: ServiceHistoryControllerGetComplimentaryServiceHistoryListParams,) => {
    return [
    `/service-history/complimentary`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getServiceHistoryControllerGetComplimentaryServiceHistoryListQueryOptions = <TData = Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError = unknown>(params: ServiceHistoryControllerGetComplimentaryServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServiceHistoryControllerGetComplimentaryServiceHistoryListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>> = ({ signal }) => serviceHistoryControllerGetComplimentaryServiceHistoryList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServiceHistoryControllerGetComplimentaryServiceHistoryListQueryResult = NonNullable<Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>>
export type ServiceHistoryControllerGetComplimentaryServiceHistoryListQueryError = unknown


export function useServiceHistoryControllerGetComplimentaryServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetComplimentaryServiceHistoryListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>,
          TError,
          Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceHistoryControllerGetComplimentaryServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetComplimentaryServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>,
          TError,
          Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceHistoryControllerGetComplimentaryServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetComplimentaryServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServiceHistoryControllerGetComplimentaryServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetComplimentaryServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetComplimentaryServiceHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServiceHistoryControllerGetComplimentaryServiceHistoryListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



