/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CarControllerGetStoreCarListParams,
  DeleteStoreCarResponse,
  GetStoreCarListResponse,
  RegisterStoreCarRequest,
  RegisterStoreCarResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const carControllerGetStoreCarList = (
    params: CarControllerGetStoreCarListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreCarListResponse>(
      {url: `/car/store`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getCarControllerGetStoreCarListQueryKey = (params?: CarControllerGetStoreCarListParams,) => {
    return [
    `/car/store`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCarControllerGetStoreCarListQueryOptions = <TData = Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError = unknown>(params: CarControllerGetStoreCarListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCarControllerGetStoreCarListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof carControllerGetStoreCarList>>> = ({ signal }) => carControllerGetStoreCarList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CarControllerGetStoreCarListQueryResult = NonNullable<Awaited<ReturnType<typeof carControllerGetStoreCarList>>>
export type CarControllerGetStoreCarListQueryError = unknown


export function useCarControllerGetStoreCarList<TData = Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError = unknown>(
 params: CarControllerGetStoreCarListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof carControllerGetStoreCarList>>,
          TError,
          Awaited<ReturnType<typeof carControllerGetStoreCarList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarControllerGetStoreCarList<TData = Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError = unknown>(
 params: CarControllerGetStoreCarListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof carControllerGetStoreCarList>>,
          TError,
          Awaited<ReturnType<typeof carControllerGetStoreCarList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarControllerGetStoreCarList<TData = Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError = unknown>(
 params: CarControllerGetStoreCarListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCarControllerGetStoreCarList<TData = Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError = unknown>(
 params: CarControllerGetStoreCarListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetStoreCarList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCarControllerGetStoreCarListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const carControllerRegisterStoreCar = (
    registerStoreCarRequest: RegisterStoreCarRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterStoreCarResponse>(
      {url: `/car/store`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerStoreCarRequest, signal
    },
      options);
    }
  


export const getCarControllerRegisterStoreCarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerRegisterStoreCar>>, TError,{data: RegisterStoreCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof carControllerRegisterStoreCar>>, TError,{data: RegisterStoreCarRequest}, TContext> => {

const mutationKey = ['carControllerRegisterStoreCar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof carControllerRegisterStoreCar>>, {data: RegisterStoreCarRequest}> = (props) => {
          const {data} = props ?? {};

          return  carControllerRegisterStoreCar(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CarControllerRegisterStoreCarMutationResult = NonNullable<Awaited<ReturnType<typeof carControllerRegisterStoreCar>>>
    export type CarControllerRegisterStoreCarMutationBody = RegisterStoreCarRequest
    export type CarControllerRegisterStoreCarMutationError = unknown

    export const useCarControllerRegisterStoreCar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerRegisterStoreCar>>, TError,{data: RegisterStoreCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof carControllerRegisterStoreCar>>,
        TError,
        {data: RegisterStoreCarRequest},
        TContext
      > => {

      const mutationOptions = getCarControllerRegisterStoreCarMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const carControllerDeleteStoreCar = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteStoreCarResponse>(
      {url: `/car/store/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getCarControllerDeleteStoreCarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerDeleteStoreCar>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof carControllerDeleteStoreCar>>, TError,{id: string}, TContext> => {

const mutationKey = ['carControllerDeleteStoreCar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof carControllerDeleteStoreCar>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  carControllerDeleteStoreCar(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CarControllerDeleteStoreCarMutationResult = NonNullable<Awaited<ReturnType<typeof carControllerDeleteStoreCar>>>
    
    export type CarControllerDeleteStoreCarMutationError = unknown

    export const useCarControllerDeleteStoreCar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerDeleteStoreCar>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof carControllerDeleteStoreCar>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCarControllerDeleteStoreCarMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    