/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetStoreMarketingProductListResponse,
  StoreMarketingProductControllerGetStoreMarketingProductListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const storeMarketingProductControllerGetStoreMarketingProductList = (
    params: StoreMarketingProductControllerGetStoreMarketingProductListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreMarketingProductListResponse>(
      {url: `/store-marketing-product`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStoreMarketingProductControllerGetStoreMarketingProductListQueryKey = (params?: StoreMarketingProductControllerGetStoreMarketingProductListParams,) => {
    return [
    `/store-marketing-product`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStoreMarketingProductControllerGetStoreMarketingProductListQueryOptions = <TData = Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError = unknown>(params: StoreMarketingProductControllerGetStoreMarketingProductListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreMarketingProductControllerGetStoreMarketingProductListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>> = ({ signal }) => storeMarketingProductControllerGetStoreMarketingProductList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreMarketingProductControllerGetStoreMarketingProductListQueryResult = NonNullable<Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>>
export type StoreMarketingProductControllerGetStoreMarketingProductListQueryError = unknown


export function useStoreMarketingProductControllerGetStoreMarketingProductList<TData = Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError = unknown>(
 params: StoreMarketingProductControllerGetStoreMarketingProductListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>,
          TError,
          Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreMarketingProductControllerGetStoreMarketingProductList<TData = Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError = unknown>(
 params: StoreMarketingProductControllerGetStoreMarketingProductListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>,
          TError,
          Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreMarketingProductControllerGetStoreMarketingProductList<TData = Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError = unknown>(
 params: StoreMarketingProductControllerGetStoreMarketingProductListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreMarketingProductControllerGetStoreMarketingProductList<TData = Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError = unknown>(
 params: StoreMarketingProductControllerGetStoreMarketingProductListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeMarketingProductControllerGetStoreMarketingProductList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreMarketingProductControllerGetStoreMarketingProductListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



