/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExpectControllerGetExpectedSalesParams,
  GetExpectedSalesResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const expectControllerGetExpectedSales = (
    params: ExpectControllerGetExpectedSalesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetExpectedSalesResponse>(
      {url: `/expect/sales`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getExpectControllerGetExpectedSalesQueryKey = (params?: ExpectControllerGetExpectedSalesParams,) => {
    return [
    `/expect/sales`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getExpectControllerGetExpectedSalesQueryOptions = <TData = Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError = unknown>(params: ExpectControllerGetExpectedSalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExpectControllerGetExpectedSalesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof expectControllerGetExpectedSales>>> = ({ signal }) => expectControllerGetExpectedSales(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExpectControllerGetExpectedSalesQueryResult = NonNullable<Awaited<ReturnType<typeof expectControllerGetExpectedSales>>>
export type ExpectControllerGetExpectedSalesQueryError = unknown


export function useExpectControllerGetExpectedSales<TData = Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError = unknown>(
 params: ExpectControllerGetExpectedSalesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expectControllerGetExpectedSales>>,
          TError,
          Awaited<ReturnType<typeof expectControllerGetExpectedSales>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExpectControllerGetExpectedSales<TData = Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError = unknown>(
 params: ExpectControllerGetExpectedSalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expectControllerGetExpectedSales>>,
          TError,
          Awaited<ReturnType<typeof expectControllerGetExpectedSales>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExpectControllerGetExpectedSales<TData = Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError = unknown>(
 params: ExpectControllerGetExpectedSalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useExpectControllerGetExpectedSales<TData = Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError = unknown>(
 params: ExpectControllerGetExpectedSalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof expectControllerGetExpectedSales>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExpectControllerGetExpectedSalesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



