/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface CrmLogCountItem {
  /** 이벤트명 */
  actionName: string;
  /** 발송 건수 */
  successCount: number;
}
