/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface DailyWeatherHistoryWeatherHistoryItem {
  /** 일시 */
  dateTime: string;
  /** 날짜 */
  date: string;
  /** 시간 */
  time: string;
  /** 날씨 */
  weatherText: string;
  /** 날씨 코드 */
  weatherCode: string;
  /** 기온 */
  temperature: number;
  /** 강수 여부 */
  hasPrecipitation: boolean;
  /**
   * 강수 유형
   * @nullable
   */
  precipitationType?: string | null;
  /** 현재 강우량 */
  currentPrecipitation: number;
}
