/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { DailyWeatherHistoryWeatherHistoryItem } from './dailyWeatherHistoryWeatherHistoryItem';

export interface DailyWeatherHistoryResult {
  /** ID */
  id: string;
  /** 날짜 */
  date: string;
  /**
   * 당일 최고 기온
   * @nullable
   */
  highestTemperature?: number | null;
  /**
   * 당일 최저 기온
   * @nullable
   */
  lowestTemperature?: number | null;
  /**
   * 당일 평균 기온
   * @nullable
   */
  averageTemperatureToday?: number | null;
  /**
   * 전날 평균 기온
   * @nullable
   */
  averageTemperature1day?: number | null;
  /**
   * 3일 평균 기온
   * @nullable
   */
  averageTemperature3day?: number | null;
  /**
   * 7일 평균 기온
   * @nullable
   */
  averageTemperature7day?: number | null;
  /**
   * 당일 누적 강우량
   * @nullable
   */
  precipitationToday?: number | null;
  /**
   * 전날 누적 강우량
   * @nullable
   */
  precipitation1day?: number | null;
  /**
   * 3일 누적 강우량
   * @nullable
   */
  precipitation3day?: number | null;
  /**
   * 7일 누적 강우량
   * @nullable
   */
  precipitation7day?: number | null;
  /** 강수 여부 */
  hasPrecipitation: boolean;
  /**
   * 강수 유형
   * @nullable
   */
  precipitationType?: string | null;
  /** 날씨 히스토리 목록 */
  weatherHistories: DailyWeatherHistoryWeatherHistoryItem[];
}
