/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface DailyFuelStockSummaryDetailFuelSales {
  /** 유종 */
  fuelType: string;
  /** 평균 판매 단가(원/L) */
  avgPricePerLiter: number;
  /** 판매량(L) */
  totalVolume: number;
  /** 매출(원) */
  totalSales: number;
}
