/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface ExpectedSalesItem {
  /** 날짜 */
  date: string;
  /** 실제 매출 */
  actualSales: number;
  /** 예상 매출 */
  expectedSales: number;
}
