/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface ExportUserListRequest {
  /** 회원 이름 */
  name?: string;
  /** 전화번호 */
  phoneNumber?: string;
  /** 대표 차량번호 */
  carNumber?: string;
  /** 탈퇴 여부 */
  isDeleted?: boolean;
  /** 정지 여부 */
  isBanned?: boolean;
  /** 마케팅 수신 여부 */
  isMarketing?: boolean;
  /** 가입일 */
  createdAt?: string;
  /** 삭제일 */
  deletedAt?: string;
  /** 정렬 기준 */
  sortBy?: string;
  /** 정렬 순서 */
  sortOrder?: string;
}
