/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface ExportPaymentListRequest {
  /** 매장 ID 목록 */
  storeIds?: string[];
  /** 매장 */
  storeName?: string;
  /** 차량번호 */
  carNumber?: string;
  /** 이용권 종류 */
  productType?: string;
  /** 서비스 종류 */
  serviceType?: string;
  /** 시작일(YYYY-MM-DD) */
  startDate?: string;
  /** 종료일(YYYY-MM-DD) */
  endDate?: string;
}
