/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface FreeWashHistoryListItem {
  /** ID */
  id: string;
  /** 결제 수단 */
  paymentMethod: string;
  /** 매장 이름 */
  storeName: string;
  /**
   * 차량 번호
   * @nullable
   */
  carNumber?: string | null;
  /** 생성일 */
  createdAt: string;
  /** 차량 메모 */
  memo?: string[];
}
