/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { FuelTypeSalesItem } from './fuelTypeSalesItem';

export interface FuelTypeSalesResult {
  /** 유종별 매출 목록 */
  fuelTypeSales: FuelTypeSalesItem[];
  /** 총 매출액 */
  totalSalesAmount: number;
}
