/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface FuelTypeFuelSalesStatItem {
  /** 날짜 */
  date: string;
  /** 전체 매출 */
  totalSales: number;
  /** 휘발유 매출 */
  gasSales: number;
  /** 경유 매출 */
  dieselSales: number;
  /** 고급유 매출 */
  premiumGasSales: number;
  /** 전일대비 증감률 */
  dailyChangeRate: number;
}
