/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { I } from './i';
import type { FuelHistoryListStoreItem } from './fuelHistoryListStoreItem';

export interface FuelHistoryListItem {
  /** ID */
  id: string;
  /** 유종 */
  fuelType: string;
  /** 리터 당 단가 */
  pricePerLiter: number;
  /** 주유량(L) */
  volume: I;
  /** 총 결제금액 */
  totalAmount: number;
  /**
   * 차량번호
   * @nullable
   */
  carNumber?: string | null;
  /** 생성일 */
  createdAt: string;
  /** 매장 정보 */
  store: FuelHistoryListStoreItem;
}
