/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetCrmLogListItem {
  /** ID */
  id: string;
  /** 대분류 */
  category: string;
  /** 소분류 */
  actionType: string;
  /** 발생 이벤트 */
  actionName: string;
  /** 성공 건수 */
  successCount: number;
  /**
   * 메타 데이터
   * @nullable
   */
  meta?: string | null;
  /** 생성일 */
  createdAt: string;
}
