/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { FuelHistoryListItem } from './fuelHistoryListItem';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetFuelHistoryListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 주유내역 목록 */
  data: FuelHistoryListItem[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
