/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { MonthlyWeatherHistoryListItem } from './monthlyWeatherHistoryListItem';

export interface GetMonthlyWeatherHistoryListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 월간 날씨 내역 목록 */
  data: MonthlyWeatherHistoryListItem[];
}
