/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { GetMoMMarketingROIResult } from './getMoMMarketingROIResult';

/**
 * 응답 데이터
 * @nullable
 */
export type GetMoMMarketingROIResponseData = GetMoMMarketingROIResult | null;
