/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { GetMoMSalesItem } from './getMoMSalesItem';

export interface GetMoMSalesResult {
  /** 당월 매출 */
  currentSales: GetMoMSalesItem;
  /** 전월 매출 */
  previousSales: GetMoMSalesItem;
}
