/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetManagedStoresSalesListItem {
  /** 매장 ID */
  storeId: string;
  /** 매장 이름 */
  storeName: string;
  /** 총 매출 */
  totalSales: number;
  /** 세차 횟수 */
  serviceCount: number;
  /** 차량당 매출 */
  salesPerService: number;
  /** 무료세차 횟수 */
  freeWashCount: number;
}
