/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetMoMMarketingROIResult {
  /** 당월 매출 */
  currentSales: number;
  /** 당월 마캐팅 지출 */
  currentBudget: number;
  /** 당월 마케팅 ROI */
  currentROI: number;
  /** 전월 매출 */
  previousSales: number;
  /** 전월 마캐팅 지출 */
  previousBudget: number;
  /** 전월 마케팅 ROI */
  previousROI: number;
}
