/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetMoMVisitResult {
  /** 당월 방문자수 */
  currentVisitors: number;
  /** 전월 방문자수 */
  previousVisitors: number;
}
