/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { OfflineTicketListItem } from './offlineTicketListItem';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetOfflineTicketListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 현장권 목록 */
  data: OfflineTicketListItem[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
