/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { PassTypeServiceStatItem } from './passTypeServiceStatItem';

export interface GetServiceStatByPassTypeResult {
  /** 이용권별 세차 횟수 */
  passTypeServiceStat: PassTypeServiceStatItem[];
  /** 전체 이용횟수 */
  totalServices: number;
}
