/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { StoreOilPriceItem } from './storeOilPriceItem';

export interface GetStoreOilPriceResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 유가 정보 */
  data: StoreOilPriceItem[];
}
