/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetServiceStatByWeekdayItem {
  /** 요일 */
  weekday: string;
  /** 세차 횟수 */
  service: number;
}
