/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { ServiceHistoryListItem } from './serviceHistoryListItem';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetServiceHistoryListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 이용내역 목록 */
  data: ServiceHistoryListItem[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
