/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetStoreAdminProfileResult {
  /** ID */
  identity: string;
  /** 이름 */
  name: string;
  /** 매장명 */
  storeName: string;
  /** 관리자 레벨 */
  level: number;
  /** 멤버쉽 */
  membership: string;
}
