/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { UserDetailItem } from './userDetailItem';

export interface GetUserDetailResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 회원 상세 정보 */
  data: UserDetailItem;
}
