/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetUsersCountResult {
  /** 전체 가입자 수 */
  totalUsersCount: number;
  /** 신규 가입자 수 */
  newUsersCount: number;
}
