/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetYoYSalesItem {
  /** 누적 매출 */
  totalSales: number;
  /** 결제 액수 */
  approvedAmount: number;
  /** 환불 액수 */
  refundedAmount: number;
}
