/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { GetYoYSalesItem } from './getYoYSalesItem';

export interface GetYoYSalesResult {
  /** 올해 매출 */
  currentSales: GetYoYSalesItem;
  /** 작년 매출 */
  previousSales: GetYoYSalesItem;
}
