/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface MarketingSpendSalesStatItem {
  /** 날짜 */
  date: string;
  /** 매출 */
  sales: number;
  /** 마케팅 지출 */
  marketingSpend: number;
  /** 순매출 */
  netSales: number;
}
