/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface MonthlySalesItem {
  /** 날짜(YYYY-MM-DD) */
  date: string;
  /** 승인 금액 */
  approvedAmount: number;
  /** 환불 금액 */
  refundedAmount: number;
}
