/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface MonthlyWeatherHistoryListItem {
  /** ID */
  id: string;
  /** 날짜 */
  date: string;
  /** 총 매출 */
  totalSales: number;
  /**
   * 당일 최고 기온
   * @nullable
   */
  highestTemperature?: number | null;
  /**
   * 당일 최저 기온
   * @nullable
   */
  lowestTemperature?: number | null;
  /**
   * 당일 평균 기온
   * @nullable
   */
  averageTemperatureToday?: number | null;
  /**
   * 당일 누적 강우량
   * @nullable
   */
  precipitationToday?: number | null;
  /** 강수 여부 */
  hasPrecipitation: boolean;
  /**
   * 강수 유형
   * @nullable
   */
  precipitationType?: string | null;
}
