/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface NoticeListItem {
  /** ID */
  id: string;
  /** 이름 */
  title: string;
  /** 내용 */
  content: string;
  /** 생성일 */
  createdAt: string;
}
