/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { PassTypeSalesItem } from './passTypeSalesItem';

export interface PassTypeSalesResult {
  /** 이용권별 매출 목록 */
  passTypeSales: PassTypeSalesItem[];
  /** 총 매출액 */
  totalSalesAmount: number;
}
