/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface PassTypeServiceStatItem {
  /** 이용권 종류 */
  passType: string;
  /** 세차횟수 */
  count: number;
}
