/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type PaymentControllerGetPaymentListParams = {
/**
 * 회원 이름
 */
userName?: string;
/**
 * 전화번호
 */
phoneNumber?: string;
/**
 * 차량번호
 */
carNumber?: string;
/**
 * 매장
 */
storeName?: string;
/**
 * 이용권 종류
 */
productType?: string;
/**
 * 서비스 종류
 */
serviceType?: string;
/**
 * 가입일
 */
createdAt?: string;
/**
 * 정렬 기준
 */
sortBy?: string;
/**
 * 정렬 순서
 */
sortOrder?: string;
/**
 * 가져올 데이터 수
 */
take: number;
/**
 * 건너뛸 데이터 수
 */
skip: number;
};
