/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface PaymentListPurchaseItem {
  /** ID */
  id: string;
  /** 할인 전 금액 */
  originalAmount: number;
  /** 할인 금액 */
  discountAmount: number;
  /** 최종 결제 금액 */
  totalAmount: number;
  /** 금액 */
  amount: number;
  /**
   * 쿠폰 종류
   * @nullable
   */
  couponType?: string | null;
  /**
   * 차량 번호
   * @nullable
   */
  carNumber?: string | null;
  /**
   * 카드사
   * @nullable
   */
  cardCompany?: string | null;
  /** 생성일 */
  createdAt: string;
}
