/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { ProductTypeSalesItem } from './productTypeSalesItem';

export interface ProductTypeSalesResult {
  /** 상품별 매출 목록 */
  productTypeSales: ProductTypeSalesItem[];
  /** 총 매출액 */
  totalSalesAmount: number;
}
