/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface ProductTypeSalesStatItem {
  /** 날짜 */
  date: string;
  /** 전체 매출 */
  totalSales: number;
  /** 프리미엄 매출 */
  premiumSales: number;
  /** 스탠다드 매출 */
  standardSales: number;
  /** 일회권 매출 */
  ticketSales: number;
  /** 현장결제 매출 */
  offlineTicketSales: number;
  /** 전일대비 증감률 */
  dailyChangeRate: number;
}
