/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface ProductTypeSalesItem {
  /** 상품 종류 */
  productType: string;
  /** 매출액 */
  salesAmount: number;
}
