/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface RefundCashPurchaseData {
  /** 매장명 */
  storeName: string;
  /** 서비스 종류 */
  serviceType: string;
  /**
   * 서비스 옵션
   * @nullable
   */
  serviceOptions: string | null;
  /** 결제수단 */
  paymentMethod: string;
  /** 결제금액 */
  amount: number;
  /** 승인일 */
  approvedAt: string;
}
