/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type SalesControllerGetMonthlySalesParams = {
/**
 * 기간(YYYY-MM)
 */
period: string;
/**
 * 매장 ID 목록
 */
storeIds?: string[];
};
