/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface SalesStatItem {
  /** 날짜 */
  date: string;
  /** 신규 매출 */
  newSales: number;
  /** 누적 매출 */
  totalSales: number;
}
