/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { ServiceHistoryListItemUser } from './serviceHistoryListItemUser';
import type { ServiceHistoryListStoreItem } from './serviceHistoryListStoreItem';

export interface ServiceHistoryListItem {
  /** ID */
  id: string;
  /** 서비스 종류 */
  serviceType: string;
  /** 이용권 종류 */
  passType: string;
  /**
   * 차량 번호
   * @nullable
   */
  carNumber?: string | null;
  /** 생성일 */
  createdAt: string;
  /**
   * 회원 정보
   * @nullable
   */
  user: ServiceHistoryListItemUser;
  /** 매장 정보 */
  store: ServiceHistoryListStoreItem;
}
