/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { ServiceHistoryListUserItem } from './serviceHistoryListUserItem';

/**
 * 회원 정보
 * @nullable
 */
export type ServiceHistoryListItemUser = ServiceHistoryListUserItem | null;
