/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface ServiceStatItem {
  /** 날짜 */
  date: string;
  /** 신규 회원 수 */
  newServices: number;
  /** 누적 회원 수 */
  totalServices: number;
}
