/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type StaffControllerGetStaffListParams = {
/**
 * 매장 ID 목록
 */
storeIds?: string[];
/**
 * 이름
 */
name?: string;
/**
 * 전화번호
 */
phoneNumber?: string;
/**
 * 가져올 데이터 수
 */
take: number;
/**
 * 건너뛸 데이터 수
 */
skip: number;
};
