/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface StoreDetailServiceOptionItem {
  /** ID */
  id: string;
  /** 옵션명 */
  optionName: string;
  /** 가격 */
  amount: number;
  /** 순서 */
  index: number;
  /** 회원전용 여부 */
  isForMembers: boolean;
}
