/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { StoreDetailItemStoreGroup } from "./storeDetailItemStoreGroup";

export interface StoreDetailItem {
  /** ID */
  id: string;
  /** 이름 */
  name: string;
  /** 전화번호 */
  phoneNumber: string;
  /** 주소 */
  address: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lng: number;
  /** 매장 종류 */
  storeType: string;
  /**
   * 대표 이미지
   * @nullable
   */
  mainImage?: string | null;
  /**
   * 태그
   * @nullable
   */
  tags?: string | null;
  /**
   * 매장 공지
   * @nullable
   */
  notice?: string | null;
  /**
   * 매장 소개
   * @nullable
   */
  description?: string | null;
  /**
   * 유의사항
   * @nullable
   */
  policy?: string | null;
  /**
   * 이용권 가격
   * @nullable
   */
  passPrice?: string | null;
  /**
   * 스탠다드 구독권 최대 사용 횟수
   * @nullable
   */
  standardMaxUsage?: number | null;
  /**
   * 영업 시간
   * @nullable
   */
  businessHours?: string | null;
  /**
   * 휴게 시간
   * @nullable
   */
  breakTime?: string | null;
  /**
   * 휴무일
   * @nullable
   */
  holidays?: string | null;
  /** 대표 이름 */
  ceoName: string;
  /** 대표 전화번호 */
  ceoPhoneNumber: string;
  /** 숨김 여부 */
  isHidden: boolean;
  /**
   * 직영 매장
   * @nullable
   */
  storeGroup: StoreDetailItemStoreGroup;
}
