/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface StoreOilPriceItem {
  /** 유종 */
  oilType: string;
  /** 판매가 */
  price: number;
  /** 기준일자 */
  priceDate: string;
  /** 기준시간 */
  priceTime: string;
}
