/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface StoreListItem {
  /** ID */
  id: string;
  /** 이름 */
  name: string;
  /** 전화번호 */
  phoneNumber: string;
  /** 주소 */
  address: string;
  /**
   * 대표 이미지
   * @nullable
   */
  mainImage?: string | null;
}
