/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface SummaryStatData {
  /** 전체 구독자 수 */
  subscriptionStat: number;
  /** 전체 가입자 수 */
  monthlySalesStat: number;
  /** 누적 매출 */
  totalSalesStat: number;
  /** 누적 이용횟수 */
  serviceStat: number;
}
