/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface TodayStoreOperationCashHistoryItem {
  /** 시재 종류 */
  type: string;
  /** 금액 */
  amount: number;
  /** 생성일 */
  createdAt: string;
}
