/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { TodayStoreOperationCashHistoryItem } from './todayStoreOperationCashHistoryItem';

export interface TodayStoreOperationResult {
  /** ID */
  id: string;
  /**
   * 세차 횟수
   * @nullable
   */
  serviceCount?: number | null;
  /** 수정일 */
  openedAt: string;
  /**
   * 삭제일
   * @nullable
   */
  closedAt?: string | null;
  /** 현금 시재내역 목록 */
  cashHistories: TodayStoreOperationCashHistoryItem[];
}
