/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UpdateFuelInventoryVolumeRequest {
  /** ID */
  id: string;
  /** 휘발유 실측재고량(L) */
  gasolineInventoryVolume: number;
  /** 경유 실측재고량(L) */
  dieselInventoryVolume: number;
  /** 고급유 실측재고량(L) */
  premiumInventoryVolume: number;
}
