/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { UpdateStoreRequestBusinessHours } from './updateStoreRequestBusinessHours';
import type { UpdateStoreRequestOfflinePrice } from './updateStoreRequestOfflinePrice';
import type { UpdateServiceOptionDto } from './updateServiceOptionDto';

export interface UpdateStoreRequest {
  /** ID */
  id: string;
  /**
   * 대표 이미지
   * @nullable
   */
  mainImage?: string | null;
  /**
   * 매장 공지
   * @nullable
   */
  notice?: string | null;
  /**
   * 매장 소개
   * @nullable
   */
  description?: string | null;
  /**
   * 유의사항
   * @nullable
   */
  policy?: string | null;
  /**
   * 휴무일
   * @nullable
   */
  holidays?: string | null;
  /**
   * 휴게 시간
   * @nullable
   */
  breakTime?: string | null;
  /** 영업 시간 */
  businessHours?: UpdateStoreRequestBusinessHours;
  /** 현장권 가격 */
  offlinePrice?: UpdateStoreRequestOfflinePrice;
  /** 서비스 옵션 목록 */
  serviceOptions?: UpdateServiceOptionDto[];
}
