/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { UpdateStoreRequestBusinessHoursOneOf } from './updateStoreRequestBusinessHoursOneOf';

/**
 * 영업 시간
 */
export type UpdateStoreRequestBusinessHours = UpdateStoreRequestBusinessHoursOneOf | unknown;
