/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { UpdateStoreRequestOfflinePriceOneOf } from './updateStoreRequestOfflinePriceOneOf';

/**
 * 현장권 가격
 */
export type UpdateStoreRequestOfflinePrice = UpdateStoreRequestOfflinePriceOneOf | unknown;
