/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

/**
 * 대표카드
 */
export type UserListItemMainCard = { [key: string]: unknown };
