/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UserCarItem {
  /** ID */
  id: string;
  /** 제조사 */
  vendor: string;
  /** 차량 종류 */
  type: string;
  /** 모델명 */
  model: string;
  /** 차량 번호 */
  number: string;
  /** 대표 차량 여부 */
  isMain: boolean;
}
