/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Partners
 * Allta Partners 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { WeeklySalesListItem } from './weeklySalesListItem';

export interface WeeklySalesListResult {
  /** 매장 매출 */
  storeSales: WeeklySalesListItem[];
  /** 전체 매출 */
  totalSales: number;
}
